config/routes.rb
Shownotes::Application.routes.draw do
  root :to => 'home#index'

  # authentication routes
  match '/login',                 :to => 'user_session#new',                      :as => :login,           :via => :get
  match '/login',                 :to => 'user_session#create',                   :as => :login,           :via => :post
  match '/logout',                :to => 'user_session#destroy',                  :as => :logout,          :via => :delete
  match '/forgot_password',       :to => 'user_session#forgot_password',          :as => :forgot_password, :via => :get
  match '/forgot_password',       :to => 'user_session#send_reset_password_link', :as => :forgot_password, :via => :post
  match '/reset_password/:token', :to => 'user_session#acquire_password',         :as => :reset_password,  :via => :get
  match '/reset_password/:token', :to => 'user_session#reset_password',           :as => :reset_password,  :via => :post
  match '/register',              :to => 'users#new',                             :as => :register,        :via => :get
  match '/register',              :to => 'users#create',                          :as => :register,        :via => :post

  # custom error routes
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#unprocessable_entity'
  match '/500' => 'errors#application_error'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :crypted_password, :email, :first_name, :last_name, :password_salt, :perishable_token, :persistence_token

  acts_as_authentic do |c|
    # because RSpec has problems with Authlogic's session maintenance
    # see https://github.com/binarylogic/authlogic/issues/262#issuecomment-1804988
    c.maintain_sessions = false
  end

  def send_password_reset_instructions!
    reset_perishable_token!
    SiteMailer.password_reset_instructions(self).deliver
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    unless current_user
      store_location
      flash[:notice] = 'You must be logged in to access this page'
      redirect_to login_url
      return false
    end
  end

  def require_no_user
    if current_user
      store_location
      flash[:notice] = 'You must be logged out to access this page'
      redirect_to root_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.request_uri
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  before_filter :find_user_by_perishable_token, :only => [:acquire_password, :reset_password]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      redirect_back_or_default root_url
    else
      flash.now[:error] = 'Username or password are incorrect.'
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to login_url
  end

  def send_reset_password_link
    @user = User.where('LOWER(email) = ?', params[:email].downcase).first
    if @user.blank?
      flash.now[:error] = "No user found with that email address."
      render :forgot_password
    else
      begin
        @user.send_password_reset_instructions!
      rescue Net::SMTPFatalError
      end
      flash[:notice] = "An email has been sent with a link to reset your password. Please check your inbox."
      redirect_to root_url
    end
  end

  def reset_password
    if @user.update_attributes(params[:user])
      flash[:success] = "Your password has been changed. Please login to continue."
      redirect_to root_url
    else
      flash.now[:error] = "There was an error updating your password."
      render :acquire_password
    end
  end

  private
    def find_user_by_perishable_token
      @user = User.find_by_perishable_token(params[:token])

      if @user.blank?
        flash[:error] = "There was a problem finding your account. The reset password link may have expired. Please try again."
        redirect_to forgot_password_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shownotes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/flash' %>
<%= yield %>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash().each do |key, msg| %>
  <div class="alert alert-<%= key %> fade in">
    <%= link_to '&times;'.html_safe, '#', :class => 'close', 'data-dismiss' => 'alert' %>
    <%= msg %>
  </div>
<% end %>

app/views/user_session/acquire_password.html.erb
<%= form_for :user, :url => reset_password_path(:token => @user.perishable_token), :html => {:method => 'post'} do |f| %>
  <fieldset>
    <legend>Reset your password</legend>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, 'Password (again)' %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit 'Update' %>
    <%= link_to 'Cancel', root_path %>
  </fieldset>
<%- end -%>

app/views/user_session/forgot_password.html.erb
<%= form_tag forgot_password_path do %>
  <fieldset>
    <legend>Forgot Password</legend>

    <%= label_tag :email, 'Enter the email you used to register' %>
    <%= email_field_tag :email, params[:email] %>

    <%= submit_tag 'Submit' %>
    <%= link_to 'Cancel', login_path %>
  </fieldset>
<%- end -%>

app/views/user_session/new.html.erb
<%= form_for @user_session do |f| %>
  <fieldset>
    <legend>Sign In</legend>

    <%= f.label :email %>
    <%= f.text_field :email %></div>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.check_box :remember_me %> <label for="signin_remember_me">Remember Me</label>

    <%= f.button 'Sign In' %>
  </fieldset>
<% end -%>

<p><%= link_to "Forgot Password?", forgot_password_path %>